// src/data/userData.js
export const allUsers = [
  {
    id: 1,
    name: "John Doe",
    role: "student",
    verified: "verified",
    kycStatus: "approved",
    active: "active",
    createdAt: "2024-01-15",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmjE6itfX2i2bWRJHdLKqnskmruxdzuQGP9sAZIIINWhFInIGYf0PM91HhylxBuVzVjj0&usqp=CAU",
  },
  {
    id: 2,
    name: "Nikisha Shrestha",
    role: "teacher",
    verified: "verified",
    kycStatus: "pending",
    active: "active",
    createdAt: "2024-02-10",
    image: null,
  },
  {
    id: 3,
    name: "Alex Brown",
    role: "owner",
    verified: "unverified",
    kycStatus: "rejected",
    active: "inactive",
    createdAt: "2024-03-05",
    image: null,
  },
  {
    id: 4,
    name: "Carol Davis",
    role: "admin",
    verified: "verified",
    kycStatus: "approved",
    active: "active",
    createdAt: "2024-01-20",
    image: null,
  },
  {
    id: 5,
    name: "Emily Foster",
    role: "employee",
    verified: "verified",
    kycStatus: "approved",
    active: "active",
    createdAt: "2024-04-12",
    image: null,
  },
  {
    id: 6,
    name: "George Harris",
    role: "student",
    verified: "unverified",
    kycStatus: "pending",
    active: "active",
    createdAt: "2024-05-08",
    image: null,
  },
  {
    id: 7,
    name: "Sarah Wilson",
    role: "teacher",
    verified: "verified",
    kycStatus: "approved",
    active: "inactive",
    createdAt: "2024-03-25",
    image: null,
  },
  {
    id: 8,
    name: "Mike Johnson",
    role: "student",
    verified: "verified",
    kycStatus: "pending",
    active: "active",
    createdAt: "2024-06-01",
    image: null,
  },
];
